---
title: "Gov 50 Final Project"
author: Darcy Lin
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---

## Proposal
Can tweets predict hate crimes? In this study, I plan to examine the extent to which hateful geo-tagged tweets can predict hate crimes. I hypothesize that, in general, hateful tweets will be a good predictor for hate crimes but that effects will vary based on how wealthy an area is. In poorer areas, I hypothesize that hateful tweets will be a better predictor than richer areas. My sample is composed of tweets and hate crimes in LA between September 2017 and September 2018. The explanatory variable is hateful tweets targeting certain characteristics in a particular geographic region. The data set has already sorted the tweets to identify racially, religiously, and sexually hateful tweets. My outcome variable is the number of hate crimes for a particular characteristic. The data set has already sorted hate crimes to identify racially, religiously, and sexual motivation. If I observe a strong correlation between hate crimes and tweets in a geographic region, I would have support for my hypothesis. If this correlation is greater in areas that are poorer than the richer areas, II will have support for the latter half of my hypothesis.

## Project thoughts

I am interested in exploring data related to the gerontocracy. I would potentially explore the following questions:
- How does the average age of civil servant in the executive, legislative, and judicial branch of the United States government compare?
- How does the average age of civil servant compare to newly elected / incumbent? 
- (Correlative relationship) How do the approval ratings of civil servants compare with ages of civil servants over time?  